version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - 4200:4200
      - 9229:9229
    env_file:
      - .env
    volumes:
      - ./:/code
    command: cd frontend && ng serve
  mongo:
    image: mongo:4.2.8
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
volumes:
  mongodb:
  mongodb_config:
